update

diff --git a/.github/workflows/rollback.yml b/.github/workflows/rollback.yml
--- a/.github/workflows/rollback.yml
+++ b/.github/workflows/rollback.yml
@@ -5,7 +5,7 @@ on:
   workflow_dispatch:
     inputs:
       version:
-        description: Specify the version to rollback to, in the format "vx.x.x" (e.g., "v0.0.1")
+        description: Specify the version to rollback to, in the format "v*.*.*" (e.g., "v0.0.1")
         type: string
         required: true
 
@@ -14,18 +14,46 @@ permissions:
   contents: read
 
 jobs:
-  rollback:
-    name: Rollback
-    uses: ./.github/workflows/deploy.yml
-    with:
-      rollback: true
-      aws-region: ${{ vars.AWS_REGION }}
-      role-to-assume: arn:aws:iam::891377174586:role/gha-role
-      ecr-repository: ${{ vars.PROJECT }}
-      image-tag: ${{ inputs.version }}
-      task-definition: ${{ vars.PROJECT }}
-      container-name: ${{ vars.PROJECT }}
-      ecs-cluster: ${{ vars.ECS_CLUSTER }}
-      ecs-service: ${{ vars.PROJECT }}
-      codedeploy-application: ${{ vars.CODEDEPLOY_APPLICATION }}
-      codedeploy-application-group: ${{ vars.CODEDEPLOY_APPLICATION_GROUP }}
+  check-version:
+    name: Validate version
+    runs-on: ubuntu-latest
+    steps:
+      - name: Validate version format
+        run: |
+          if [[ ! ${{ inputs.version }} =~ ^v([1-9][0-9]*|0)\.([1-9][0-9]*|0)\.([1-9][0-9]*|0)$ ]]; then
+            echo "Invalid version format. version tag starts with \"v\" and is followed by three dot-separated numbers," \
+                 " each of which is either \"0\" or a non-zero number without leading zeros. (e.g., 'v1.0.0')."
+            exit 1
+          fi
+
+          echo "Version format is valid: ${{ inputs.version }}
+
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-region: ${{ vars.aws-region }}
+          role-to-assume: arn:aws:iam::891377174586:role/gha-role
+
+      - name: Login to Amazon ECR
+        id: login-ecr
+        uses: aws-actions/amazon-ecr-login@v2
+
+      - name: Check version existed in AWS ECR repository
+        run: aws ecr describe-images --repository-name ${{ vars.PROJECT }} --image-ids imageTag=${{ inputs.version }}
+
+  # rollback:
+  #   name: Rollback
+  #   needs: [check-version]
+  #   uses: ./.github/workflows/deploy.yml
+  #   with:
+  #     rollback: true
+  #     aws-region: ${{ vars.AWS_REGION }}
+  #     role-to-assume: arn:aws:iam::891377174586:role/gha-role
+  #     ecr-repository: ${{ vars.PROJECT }}
+  #     image-tag: ${{ inputs.version }}
+  #     task-definition: ${{ vars.PROJECT }}
+  #     container-name: ${{ vars.PROJECT }}
+  #     ecs-cluster: ${{ vars.ECS_CLUSTER }}
+  #     ecs-service: ${{ vars.PROJECT }}
+  #     codedeploy-application: ${{ vars.CODEDEPLOY_APPLICATION }}
+  #     codedeploy-application-group: ${{ vars.CODEDEPLOY_APPLICATION_GROUP }}
